spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
management:
  endpoint:
    health:
      show-details: always
